// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcnqKsYQIx376G8ZJ8L_5VThc-l8ROrYw',
    appId: '1:832804721699:web:0e0de8aad0ba581ea6cd96',
    messagingSenderId: '832804721699',
    projectId: 'myeventapp-bdbb6',
    authDomain: 'myeventapp-bdbb6.firebaseapp.com',
    storageBucket: 'myeventapp-bdbb6.firebasestorage.app',
    measurementId: 'G-WTQQEV1QWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL2O7wwokCxGkH8XxcDthczOVgbLAhyvQ',
    appId: '1:832804721699:android:7fba27cbee679b2fa6cd96',
    messagingSenderId: '832804721699',
    projectId: 'myeventapp-bdbb6',
    storageBucket: 'myeventapp-bdbb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeO-w684jd6KBB9eps8IdCyDUp63RWn8Q',
    appId: '1:832804721699:ios:8d43372207939698a6cd96',
    messagingSenderId: '832804721699',
    projectId: 'myeventapp-bdbb6',
    storageBucket: 'myeventapp-bdbb6.firebasestorage.app',
    iosBundleId: 'com.example.myEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeO-w684jd6KBB9eps8IdCyDUp63RWn8Q',
    appId: '1:832804721699:ios:8d43372207939698a6cd96',
    messagingSenderId: '832804721699',
    projectId: 'myeventapp-bdbb6',
    storageBucket: 'myeventapp-bdbb6.firebasestorage.app',
    iosBundleId: 'com.example.myEventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcnqKsYQIx376G8ZJ8L_5VThc-l8ROrYw',
    appId: '1:832804721699:web:6c71769352cbdc12a6cd96',
    messagingSenderId: '832804721699',
    projectId: 'myeventapp-bdbb6',
    authDomain: 'myeventapp-bdbb6.firebaseapp.com',
    storageBucket: 'myeventapp-bdbb6.firebasestorage.app',
    measurementId: 'G-LWJJ89WW45',
  );

}